### ISSUE TITLE
Emoticon replacement script sometimes replaces text with "undefined"

### ISSUE THREAD

**Issue by andrewliden** [JermaSites/ai-guess#1]
The regular expression performs a case insensitive match, but the map is case sensitive.  So, sometimes matches will get replaced with "undefined" instead of the expected emoticon.

As an example, the emoticon "chatpls" would get replaced with undefined, because in the map it's listed as "ChatPls".

There's a lot of ways to fix this, but probably the easiest fix would be:

1. make all the map key names lower case

then

2. change your replacer function to 
`var replacer = value => map[value.toLowerCase()]`

**Comment by sticks-stuff** [comment]
I think just removing the `i` from the regex would suffice as that would force case-sensitivity, like how Twitch already does

**Comment by andrewliden** [comment]
Yeah. I wasn't sure if there was anything that needed the case sensitivy, like maybe some of the Ai generated responses capitalizing the emoticons wrongly or something.

If that's not the case, switching to case sensitive is definitely the easiest fix.
